Feature1
Berucan/Hello-Microverse pull request #1
Opened 2022-01-06 06:28 UTC by Berucan

This is my first pull request

2022-01-06 06:58 UTC, elmar8287 requested changes
Hi @Berucan ,

Great work on making the project requirements 👏 

There are still some requirements that aren't done yet, please work on it and ask for another review.
      
 ## Required Changes ♻️

- [ ] Please, consider comments under review
- [ ] Please, modify your README file, make it more informative. My suggestions are to add your information of social network links, delete some empty, not-needed lines.
<img width="877" alt="Screen Shot 2022-01-06 at 10 45 06" src="https://user-images.githubusercontent.com/49064106/148341925-cd1a0c2d-c474-4693-8292-c26ce8e4450f.png">

- [ ] Please, consider that the PR (Pull Request) should have a descriptive title telling you what changes are inside.
- [ ] Please, consider that the PR should have a short summary describing introduced changes in more detail. You have not provided a description.


#### _**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**_

## Optional suggestions

- N/A

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------------------------------------------------------------------------------------------------------------------------------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

2022-01-06 06:58 UTC, elmar8287 commented on index.html
> +  </body>
- [ ] Please, use correct structure of HTML file. You should also close `html` tag. Also, please, insert all tags inside of `body` tag. Your `header` tag is outside of `body` tag.
- You can see this issue information in linter error
<img width="861" alt="Screen Shot 2022-01-06 at 10 46 02" src="https://user-images.githubusercontent.com/49064106/148340815-9e61b78c-f37c-4ae3-acab-c15eba40407f.png">

2022-01-06 06:58 UTC, elmar8287 commented on index.html
> +  </head>
- [ ] Please, consider, that a `viewport` meta element is not specified.

2022-01-06 06:58 UTC, elmar8287 commented on style.css
> +}
- [ ] Please, consider linter errors
<img width="940" alt="Screen Shot 2022-01-06 at 10 50 12" src="https://user-images.githubusercontent.com/49064106/148341434-2c175ae2-b361-454d-a450-b76ff4ed3526.png">

2022-01-06 12:05 UTC, elmar8287 requested changes
Hi @Berucan ,

Great work on making the project requirements 👏 

There are still some requirements that aren't done yet, please work on it and ask for another review.
      
 ## Required Changes ♻️

- [ ] Please, consider comments under review
- [ ] Please, fix your PR title and description, as I mentioned in the previous review. Do it more informative. Something like `In this PR I added HTML file with h1 tag with ..... ` and also `I modified README file, add the project description ....` - hope you understand my suggestions.

This is your PR:

<img width="933" alt="Screen Shot 2022-01-06 at 15 42 30" src="https://user-images.githubusercontent.com/49064106/148379798-e7f2377d-c521-4937-8e15-fbb8589e4a33.png">
Please, edit the title and description. 


#### _**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**_

## Optional suggestions

- N/A

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------------------------------------------------------------------------------------------------------------------------------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

2022-01-06 12:05 UTC, elmar8287 commented on index.html
> +  </head>
- [ ] Here you have again an issue with a linter. It asks you to add a `viewport ` meta tag. Please, add into your `head` section the following:

` <meta name="viewport" content="width=device-width, initial-scale=1.0">` and also correct the link to your .css file. This is correct one `<link rel="stylesheet" href="style.css">`

Please, also add `lang="en"` in HTML tag in beginning. It should looks like this `<html lang="en">` - you can fix by this the warning message from linter

2022-01-06 12:05 UTC, elmar8287 commented on style.css
> +
- [ ] Please, fix the linter, as I mentioned in the previous review. You have empty lines in it. Please, before pushing it, you can run `npx stylelint "**/*.{css,scss}"` command in terminal and check any linter errors and fix them before.

2022-01-06 14:11 UTC, closed without merging

2022-01-07 06:04 UTC, Berucan commented
Good morning,
I wanted to say thank you for all the review comments you gave me. I got my
work approved.

On Thu, 6 Jan 2022 at 15:05, Elmar Abdulkarimov ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> Hi @Berucan <https://github.com/Berucan> ,
>
> Great work on making the project requirements 👏
>
> There are still some requirements that aren't done yet, please work on it
> and ask for another review.
> Required Changes ♻️
>
>    - Please, consider comments under review
>    - Please, fix your PR title and description, as I mentioned in the
>    previous review. Do it more informative. Something like In this PR I
>    added HTML file with h1 tag with ..... and also I modified README
>    file, add the project description .... - hope you understand my
>    suggestions.
>
> This is your PR:
>
> [image: Screen Shot 2022-01-06 at 15 42 30]
> <https://user-images.githubusercontent.com/49064106/148379798-e7f2377d-c521-4937-8e15-fbb8589e4a33.png>
> Please, edit the title and description. *Please, do not open a new Pull
> Request for re-reviews. You should use the same Pull Request submitted for
> the first review, either valid or invalid unless it is requested otherwise.* Optional
> suggestions
>
>    - N/A
>
> *Every comment with the [OPTIONAL] prefix won't stop the approval of this
> PR. However, I strongly recommend you to take them into account as they can
> make your code better. Some of them were simply missed by the previous
> reviewer and addressing them will really improve your application.*
>
> Cheers and Happy coding!👏👏👏
>
> Feel free to leave any questions or comments in the PR thread if something
> is not 100% clear.
> ------------------------------
>
> As described in the Code reviews limits policy
> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have
> a limited number of reviews per project (check the exact number in your
> Dashboard). If you think that the code review was not fair, you can request
> a second opinion using this form. <https://airtable.com/shrQAqnBwek5a0O0s>
> ------------------------------
>
> In index.html
> <https://github.com/Berucan/Hello-Microverse/pull/1#discussion_r779494456>
> :
>
> > +  <head>
>
> +    <meta charset="UTF-8">
>
> +    <title>Hello Microverese</title>
>
> +    <link rel="stylesheet" href="css/style.css">
>
> +  </head>
>
>
>
>    - Here you have again an issue with a linter. It asks you to add a viewport
>    meta tag. Please, add into your head section the following:
>
> <meta name="viewport" content="width=device-width, initial-scale=1.0">
> and also correct the link to your .css file. This is correct one <link
> rel="stylesheet" href="style.css">
>
> Please, also add lang="en" in HTML tag in beginning. It should looks like
> this <html lang="en"> - you can fix by this the warning message from
> linter
> ------------------------------
>
> In style.css
> <https://github.com/Berucan/Hello-Microverse/pull/1#discussion_r779496476>
> :
>
> > +
>
> +.headerOne { color: aqua; }
>
> +
>
> +
>
>
>
>    - Please, fix the linter, as I mentioned in the previous review. You
>    have empty lines in it. Please, before pushing it, you can run npx
>    stylelint "**/*.{css,scss}" command in terminal and check any linter
>    errors and fix them before.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Berucan/Hello-Microverse/pull/1#pullrequestreview-845552089>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AWESXPY2XUF6OLBDZH34FRTUUWARTANCNFSM5LLTRTUQ>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>